name: C/C++ CI

on: [push]

jobs:
  build:
    env:
      DEVKITPRO: /opt/devkitpro

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Download DEVKITPRO
      run: wget https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb
    - name: Install DKP
      run: sudo dpkg -i devkitpro-pacman.deb
    - name: Install packages
      run: printf "\nY" | sudo dkp-pacman -Sy switch-dev switch-mbedtls
    - name: make
      run: make LATESTTAG=Beta

    - name: Upload Release
      uses: Genwald/create-release@eba889c
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: beta
        code: beta
        body: Latest commit, automatically updated. May not be fully tested or fully working.
        prerelease: true
        recreate: true
        assets: Ultimate_Mod_Manager.nro:Ultimate_Mod_Manager.nro:application/octet-stream
